const SET_MAP_POSITION = 'SET_MAP_POSITION';
const IS_CREATE_PLACE_MODE = 'IS_CREATE_PLACE_MODE';
const POST_PLACE = 'POST_PLACE';
const SET_CURRENT_PLACE_POSITION = 'SET_CURRENT_PLACE_POSITION';
const LOAD_PLACES = 'LOAD_PLACES';

export {
	SET_MAP_POSITION,
	IS_CREATE_PLACE_MODE,
	POST_PLACE,
	SET_CURRENT_PLACE_POSITION,
	LOAD_PLACES,
};
